from pynput.keyboard import Key, Controller

from pynput.keyboard import Listener
import time


def tryCastInvoker(text, keyboard):
    if text == "камень" or text == "meteor":
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.02)
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.03)
        keyboard.press("w")
        keyboard.release("w")
        time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.15)
        keyboard.press("d")
        keyboard.release("d")
    elif text.lower() == "снег" or text.lower() == "coldsnap":
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.02)
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.03)
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.15)
        keyboard.press("d")
        keyboard.release("d")
    elif text.lower() == "луч":
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.02)
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.03)
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.15)
        keyboard.press("d")
        keyboard.release("d")
    elif text.lower() == "стена":
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.02)
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.03)
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.15)
        keyboard.press("d")
        keyboard.release("d")
    elif text.lower() == "торнадо":
        keyboard.press("w")
        keyboard.release("w")
        time.sleep(0.02)
        keyboard.press("w")
        keyboard.release("w")
        time.sleep(0.03)
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.15)
        keyboard.press("d")
        keyboard.release("d")
    elif text.lower() == "невидимость":
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.02)
        keyboard.press("w")
        keyboard.release("w")
        time.sleep(0.03)
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.02)
        keyboard.press("w")
        keyboard.release("w")
        time.sleep(0.03)
        keyboard.press("w")
        keyboard.release("w")
        time.sleep(0.02)
        keyboard.press("w")
        keyboard.release("w")
        time.sleep(0.15)
        keyboard.press("d")
        keyboard.release("d")
    elif text.lower() == "бласт" or text.lower() == "blast":
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.02)
        keyboard.press("w")
        keyboard.release("w")
        time.sleep(0.03)
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.15)
        keyboard.pdwwress("d")
        keyboard.release("d")
    elif text.lower() == "духи" or text.lower() == "blast":
        keyboard.press("q")
        keyboard.release("q")
        time.sleep(0.02)
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.03)
        keyboard.press("e")
        keyboard.release("e")
        time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.15)
        keyboard.press("d")
        keyboard.release("d")
    elif text.lower() == "минус" or text.lower() == "emp":
        for i in range(3):
            keyboard.press("w")
            keyboard.release("w")
            time.sleep(0.02)
        keyboard.press("r")
        keyboard.release("r")
        time.sleep(0.15)
        keyboard.press("d")
        keyboard.release("d")
    time.sleep(0.15)